# OpenAI API Key
OPENAI_API_KEY = "your-openai-api-key"

# Security
JWT_SECRET_KEY = "your-secure-random-secret-key"  # Generate a secure random key
ADMIN_PASSWORD = "your-secure-admin-password"     # Set a strong admin password

# Optional: Database credentials if you want to use a database later
# DB_USERNAME = ""
# DB_PASSWORD = ""
# DB_HOST = ""
# DB_NAME = "" 